# ANCHOR Project information
site_name: Tyler Nguyen's Webpage
site_url: https://tylernguyen.xyz
site_author: Tyler Nguyen
site_description: >-
  Tyler is a high consumer of popular culture, history, and the internet;
  He has much to say, so he writes instead of annoying the uninterested.

# ANCHOR  Repository
repo_name: tylernguyen.xyz
repo_url: https://github.com/tylernguyen/tylernguyen.xyz
edit_uri: "edit/main/docs/"

copyright: Copyright &copy; 2022 Tyler Nguyen

# ANCHOR Customization
extra:
  tags:
    internet: internet
    keyboard: keyboard
    network: network
    open source: opensource
    selfhosted: selfhosted
    vpn: vpn
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tylernguyen
  generator: false # NOTE Hide "Made with Material for MkDocs"

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-square
    tag:
      internet: fontawesome/brands/internet-explorer
      keyboard: fontawesome/regular/keyboard
      network: fontawesome/solid/network-wired
      opensource: fontawesome/brands/git
      selfhosted: fontawesome/solid/server
      vpn: material/tunnel
  font:
    text: Roboto
    code: Fira Code
  palette:
    - scheme: default
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - announce.dismiss # NOTE Dismissable Announcement Banner
    - search.highlight # NOTE Highlight Matched Occurences after a Search
    - search.suggest
    - navigation.instant # NOTE Instant Loading on Internal Links with XMLHttpRequest (XHR)
    - navigation.sections
    - navigation.top # NOTE Back-to-top button
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking # NOTE Update URL with Active Anchor
    - toc.follow # NOTE Anchor following in TOC

extra_css:
  - stylesheets/extra.css

# ANCHOR Plugins
plugins:
  - git-revision-date-localized
  - privacy
  - search
  - social
  - tags

# SECTION Extensions
markdown_extensions:
  # NOTE Python Markdown
  - admonition
  - attr_list # NOTE Grid, Annotations, Images, Buttons,
  - md_in_html # NOTE Grid, Annotations, Images
  - footnotes
  - meta # NOTE YAML Front Matter

 # NOTE Python Markdown Extensions
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.snippets: # NOTE Glossary, Embed External Files
      - base_path: docs/assets/snippets/
      - check_paths: true
  - pymdownx.superfences: # NOTE Admoniton, Annotations, MermaidJS
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
# !SECTION

# ANCHOR Page tree
nav:
    - Home: 
      - index.md
      - 2022:
        - blog/2022/email-workflow-for-the-modern-internet.md
        - blog/2022/cloudflare-remote-access-suite.md
    - Catalog:
      - Websites: catalog/websites.md
      - Books : catalog/books.md
      - Movies : catalog/movies.md
      - Television: catalog/television.md
      - Anime: catalog/anime.md
      - Comics: catalog/comics.md
      - Manga: catalog/manga.md
      - Graphic Novels: catalog/graphic-novels.md
      - Music: catalog/music.md
    - Uses This:
      - Hardware : uses-this/hardware.md
      - Software : uses-this/software.md
      - Services : uses-this/services.md
      - Self-Hosted : uses-this/selfhosted.md
      - Security : uses-this/security.md
      - Don't Use This: uses-this/dont-use-this.md
      - dotfiles:
        - .keyboard: uses-this/keyboard.md
        - .cli: uses-this/cli.md
    - Contact: contact.md
    - Credits: credits.md
    - Support: https://github.com/sponsors/tylernguyen
    - About: about.md
