# ANCHOR Project information
site_name: damn that television.
site_url: https://tylernguyen.dev
site_author: Tyler Nguyen
site_description: >-
  damn that television. is a Tyler Nguyen blog production, 
  himself directed and alone edited.

# ANCHOR  Repository
repo_name: tylernguyen/damnthattelevision.com
repo_url: https://github.com/tylernguyen/damnthattelevision.com
edit_uri: ""

theme:
  name: material
  icon:
    repo: fontawesome/brands/git
    logo: material/laptop
  custom_dir: overrides
  font:
    text: Roboto Slab
    code: Fira Code
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: red
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - announce.dismiss # NOTE Dismissable Announcement Banner
    - search.highlight # NOTE Highlight Matched Occurences after a Search
    - search.suggest
    - navigation.instant # NOTE Instant Loading on Internal Links with XMLHttpRequest (XHR)
    - navigation.sections
    - navigation.top # NOTE Back-to-top button
    - navigation.tracking # NOTE Update URL with Active Anchor
    - toc.follow # NOTE Anchor following in TOC

# ANCHOR Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tylernguyen
  # NOTE Hide "Made with Material for MkDocs"
  extra:
    generator: false

extra_css:
  - stylesheets/extra.css

# ANCHOR Plugins
plugins:
  - git-revision-date-localized
  - privacy
  - search
  - social
  - tags

# SECTION Extensions
markdown_extensions:
  # NOTE Python Markdown
  - admonition
  - attr_list # NOTE Grid, Annotations, Images, Buttons,
  - md_in_html # NOTE Grid, Annotations, Images
  - footnotes
  - meta # NOTE YAML Front Matter

 # NOTE Python Markdown Extensions
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences: # NOTE Admoniton, Annotations, MermaidJS
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
# !SECTION

# ANCHOR Page tree
nav:
    - Home: blog/index.md
