# ANCHOR Project information
site_name: Tyler Nguyen's Webpage
site_url: https://tylernguyen.xyz
site_author: Tyler Nguyen
site_description: >-
  Tyler is a high consumer of popular culture, history, and the internet;
  He has much to say, so he writes instead of annoying the uninterested.

# ANCHOR  Repository
repo_name: tylernguyen.xyz
repo_url: https://github.com/tylernguyen/tylernguyen.xyz
edit_uri: "edit/main/docs/"

copyright: Copyright &copy; 2022 Tyler Nguyen

# ANCHOR Customization
extra:
  tags:
    internet: internet
    network: network
    open source: opensource
    selfhosted: selfhosted

theme:
  name: material
  custom_dir: material
  favicon: assets/favicon.png
  icon:
    logo: material/human-greeting
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
    tag:
      internet: fontawesome/brands/internet-explorer
      network: fontawesome/solid/network-wired
      opensource: fontawesome/brands/git
      selfhosted: fontawesome/solid/server
  font:
    text: Roboto Flex
    code: Fira Code
  palette:
    - scheme: default
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - announce.dismiss # NOTE Dismissable Announcement Banner
    - search.highlight # NOTE Highlight Matched Occurences after a Search
    - search.suggest
    - navigation.indexes # NOTE Attach Top Level Doc to Section
    - navigation.instant # NOTE Instant Loading on Internal Links with XMLHttpRequest (XHR)
    - navigation.sections
    - navigation.top # NOTE Back-to-top button
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking # NOTE Update URL with Active Anchor
    - toc.follow # NOTE Anchor following in TOC

extra_css:
  - stylesheets/extra.css

# ANCHOR Plugins
plugins:
  - git-revision-date-localized
  - privacy
  - search
  - social
  - tags

# SECTION Extensions
markdown_extensions:
  # NOTE Python Markdown
  - admonition
  - attr_list # NOTE Grid, Annotations, Images, Buttons,
  - md_in_html # NOTE Grid, Annotations, Images
  - footnotes
  - meta # NOTE YAML Front Matter

 # NOTE Python Markdown Extensions
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.highlight:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences: # NOTE Admoniton, Annotations, MermaidJS
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
# !SECTION

# ANCHOR Page tree
nav:
    - Home:
      - index.md
      - 2022:
        - blog/2022/emails-as-passwords.md
        - blog/2022/cloudflare-zero-trust.md
    - Catalog:
      - Websites: websites.md
      - Books : books.md
      - Movies : movies.md
      - Television: tv.md
      - Anime: anime.md
      - Comics: comics.md
      - Manga: manga.md
      - Graphic Novels: graphic-novels.md
      - Music: music.md
    - Uses This:
      - dotfiles: dotfiles.md
      - Hardware : hardware.md
      - Software : software.md
      - Services : services.md
      - Self-Hosted : selfhosted.md
    - Now: now.md
    - Contact: contact.md
    - About: about.md
    - Support: https://github.com/sponsors/tylernguyen
    - Credits: credits.md
