# ANCHOR Project information
site_name: Tyler Nguyen's Webpage
site_url: https://tylernguyen.xyz
site_author: Tyler Nguyen
site_description: >-
  Tyler is a high consumer of popular culture, history, and the internet;
  He has much to say, so he writes instead of annoying the uninterested.

# ANCHOR  Repository
repo_name: tylernguyen.xyz
repo_url: https://github.com/tylernguyen/tylernguyen.xyz
edit_uri: ""

theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/git-square
  font:
    text: Playfair Display
    code: Fira Code
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - announce.dismiss # NOTE Dismissable Announcement Banner
    - search.highlight # NOTE Highlight Matched Occurences after a Search
    - search.suggest
    - navigation.instant # NOTE Instant Loading on Internal Links with XMLHttpRequest (XHR)
    - navigation.sections
    - navigation.top # NOTE Back-to-top button
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking # NOTE Update URL with Active Anchor
    - toc.follow # NOTE Anchor following in TOC

# ANCHOR Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tylernguyen
  extra:
    generator: false # NOTE Hide "Made with Material for MkDocs"

extra_css:
  - stylesheets/extra.css

# ANCHOR Plugins
plugins:
  - git-revision-date-localized
  - privacy
  - search
  - social
  - tags

# SECTION Extensions
markdown_extensions:
  # NOTE Python Markdown
  - admonition
  - attr_list # NOTE Grid, Annotations, Images, Buttons,
  - md_in_html # NOTE Grid, Annotations, Images
  - footnotes
  - meta # NOTE YAML Front Matter

 # NOTE Python Markdown Extensions
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences: # NOTE Admoniton, Annotations, MermaidJS
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
# !SECTION

# ANCHOR Page tree
nav:
    - Home: index.md
    - Blog:
      - 'Blog': 'blog/index.md'
      - '2022':
        - 'April':
          - 'Cloudflare Tunnels, Zero Trust, and Warp': 'blog/2022/cloudflare-tunnels-zero-trust-and-warp.md'
    - Catalog:
      - Books : catalog/books.md
      - Movies : catalog/movies.md
      - Television: catalog/television.md
      - Comics: catalog/comics.md
      - Manga: catalog/manga.md
    - Uses This:
      - Hardware : uses-this/hardware.md
      - Software : uses-this/software.md
      - Services : uses-this/services.md
      - Self-Hosted : uses-this/selfhosted.md
      - Privacy : uses-this/privacy.md
      - Security : uses-this/security.md
    - Contact: contact.md
    - Credits: credits.md
    - Support: support.md
    - About: about.md
